name: ${APP_NAME}
services:
  nginx:
    container_name: ${APP_NAME}-nginx
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - ${NGINX_PORT}:${NGINX_PORT}
    volumes:
      - ../../../nginx/development.config.nginx:${TEMPLATE_PATH}
      - type: volume
        source: nginx-data
        target: /etc/nginx/
    environment:
      - TEMPLATE_PATH=${TEMPLATE_PATH}
      - NGINX_PORT=${NGINX_PORT}
      - FRONTEND_IP=${APP_NAME}-dev:${FRONTEND_PORT}
      - BACKEND_IP=${APP_NAME}-dev:${BACKEND_PORT}
      
  server:
    env_file: .env
    container_name: ${APP_NAME}-dev
    image: ${APP_NAME}-dev
    build:
      context: .
    ports:
      - ${FRONTEND_PORT}:${FRONTEND_PORT}
      - ${BACKEND_PORT}:${BACKEND_PORT}
    volumes:
      - type: bind
        source: ../../..
        target: /usr/src/app
    depends_on:
      db:
        condition: service_healthy
  db:
    container_name: ${APP_NAME}-db
    image: postgres:18.1
    restart: always
    user: ${DB_USER}
    volumes:
      - db-data:/var/lib/postgresql
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
    ports:
      - ${DB_PORT}:${DB_PORT}
    expose:
      - ${DB_PORT}
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  db-data:
  nginx-data:


